// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_home_power.proto

package be.smarthome;

public interface PowerConsumerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:be.smarthome.PowerConsumer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>int32 threshold = 2;</code>
   * @return The threshold.
   */
  int getThreshold();

  /**
   * <code>bool enabled = 3;</code>
   * @return The enabled.
   */
  boolean getEnabled();

  /**
   * <code>bool criticalDevice = 4;</code>
   * @return The criticalDevice.
   */
  boolean getCriticalDevice();
}
