// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_home_power.proto

package be.smarthome;

public interface PowerConsumptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:be.smarthome.PowerConsumption)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 powerConsumptionValue = 1;</code>
   * @return The powerConsumptionValue.
   */
  int getPowerConsumptionValue();
}
