// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_home_power.proto

package be.smarthome;

public final class SmartHomePower {
  private SmartHomePower() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_smarthome_PowerConsumer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_be_smarthome_PowerConsumer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_smarthome_SolarProduction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_be_smarthome_SolarProduction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_smarthome_PowerConsumption_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_be_smarthome_PowerConsumption_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026smart_home_power.proto\022\014be.smarthome\"W" +
      "\n\rPowerConsumer\022\n\n\002id\030\001 \001(\t\022\021\n\tthreshold" +
      "\030\002 \001(\005\022\017\n\007enabled\030\003 \001(\010\022\026\n\016criticalDevic" +
      "e\030\004 \001(\010\"/\n\017SolarProduction\022\034\n\024solarProdu" +
      "ctionValue\030\001 \001(\005\"1\n\020PowerConsumption\022\035\n\025" +
      "powerConsumptionValue\030\001 \001(\0052\310\001\n\026PowerMan" +
      "agementService\022U\n\027newSolarProductionValu" +
      "e\022\035.be.smarthome.SolarProduction\032\033.be.sm" +
      "arthome.PowerConsumer\022W\n\030newPowerConsump" +
      "tionValue\022\036.be.smarthome.PowerConsumptio" +
      "n\032\033.be.smarthome.PowerConsumerB\002P\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_be_smarthome_PowerConsumer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_be_smarthome_PowerConsumer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_be_smarthome_PowerConsumer_descriptor,
        new java.lang.String[] { "Id", "Threshold", "Enabled", "CriticalDevice", });
    internal_static_be_smarthome_SolarProduction_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_be_smarthome_SolarProduction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_be_smarthome_SolarProduction_descriptor,
        new java.lang.String[] { "SolarProductionValue", });
    internal_static_be_smarthome_PowerConsumption_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_be_smarthome_PowerConsumption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_be_smarthome_PowerConsumption_descriptor,
        new java.lang.String[] { "PowerConsumptionValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
