// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_home_power.proto

package be.smarthome;

public interface SolarProductionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:be.smarthome.SolarProduction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 solarProductionValue = 1;</code>
   * @return The solarProductionValue.
   */
  int getSolarProductionValue();
}
